name: Android CI - AION

on:
  push:
    branches: [ "main", "capy/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install CMake and Ninja
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Uploading Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: AION-Debug-APK
        path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace
      continue-on-error: true

    - name: Uploading Release APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: AION-Release-APK
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk
      continue-on-error: true
